spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/halo-cvc/db/halo_cvc;AUTO_SERVER=TRUE
    username: admin
    password: 123456

    # MySQL database configuration.
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/halo_cvc?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
        # 解决getById 延迟加载问题
        enable_lazy_load_no_trans: true
        generate_statistics: true
        stat: debug
        # Second Level Cache - Ehcache
        #1. enable second level cache
        cache:
          use_second_level_cache: true
          #2. specify the caching framework - EhCache
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      #3. Only cache what I tell to cache.
      #javax.persistence.sharedCache.mode: ENABLE_SELECTIVE

logging:
  level.net.sf.ehcache: debug
